<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v24/enums/youtube_video_privacy.proto

namespace Google\Ads\GoogleAds\V24\Enums\YouTubeVideoPrivacyEnum;

use UnexpectedValueException;

/**
 * Describes the privacy status of a YouTube video.
 *
 * Protobuf type <code>google.ads.googleads.v24.enums.YouTubeVideoPrivacyEnum.YouTubeVideoPrivacy</code>
 */
class YouTubeVideoPrivacy
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * The value is unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    const UNKNOWN = 1;
    /**
     * Video is public.
     *
     * Generated from protobuf enum <code>PUBLIC = 2;</code>
     */
    const PBPUBLIC = 2;
    /**
     * Video is unlisted.
     *
     * Generated from protobuf enum <code>UNLISTED = 3;</code>
     */
    const UNLISTED = 3;

    private static $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::PBPUBLIC => 'PUBLIC',
        self::UNLISTED => 'UNLISTED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', self::class, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string) $name);
        if (!defined($const)) {
            $pbconst =  self::class. '::PB' . strtoupper((string) $name);
            if (!defined($pbconst)) {
                throw new UnexpectedValueException(sprintf(
                        'Enum %s has no value defined for name %s', self::class, $name));
            }
            return constant($pbconst);
        }
        return constant($const);
    }
}

