<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v19/enums/conversion_customer_type.proto

namespace Google\Ads\GoogleAds\V19\Enums\ConversionCustomerTypeEnum;

use UnexpectedValueException;

/**
 * Enumerates conversion customer types.
 *
 * Protobuf type <code>google.ads.googleads.v19.enums.ConversionCustomerTypeEnum.ConversionCustomerType</code>
 */
class ConversionCustomerType
{
    /**
     * Not specified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * The value is unknown in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    const UNKNOWN = 1;
    /**
     * Converting user is new to the advertiser.
     *
     * Generated from protobuf enum <code>NEW = 2;</code>
     */
    const PBNEW = 2;
    /**
     * Converting user is returning to the advertiser. Definition of returning
     * differs among conversion types, such as a second store visit versus a
     * second online purchase.
     *
     * Generated from protobuf enum <code>RETURNING = 3;</code>
     */
    const RETURNING = 3;

    private static $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
        self::PBNEW => 'NEW',
        self::RETURNING => 'RETURNING',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value
            )
            );
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string)$name);
        if (!defined($const)) {
            $pbconst = self::class . '::PB' . strtoupper((string)$name);
            if (!defined($pbconst)) {
                throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s',
                    self::class,
                    $name
                )
                );
            }
            return constant($pbconst);
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ConversionCustomerType::class, \Google\Ads\GoogleAds\V19\Enums\ConversionCustomerTypeEnum_ConversionCustomerType::class);

