<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v20/errors/campaign_customizer_error.proto

namespace Google\Ads\GoogleAds\V20\Errors\CampaignCustomizerErrorEnum;

use UnexpectedValueException;

/**
 * Enum describing possible campaign customizer errors.
 *
 * Protobuf type <code>google.ads.googleads.v20.errors.CampaignCustomizerErrorEnum.CampaignCustomizerError</code>
 */
class CampaignCustomizerError
{
    /**
     * Enum unspecified.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * The received error code is not known in this version.
     *
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    const UNKNOWN = 1;

    private static $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::UNKNOWN => 'UNKNOWN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value
            )
            );
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string)$name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                self::class,
                $name
            )
            );
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CampaignCustomizerError::class, \Google\Ads\GoogleAds\V20\Errors\CampaignCustomizerErrorEnum_CampaignCustomizerError::class);

